### ISSUE TITLE
version 5.4.2 not rendering

### ISSUE THREAD

**Issue by zdm** [amcharts/amcharts5#1044]
**Question**
Amchart `v6.4.2` just not rendering, shows nothing. Without any errors.

`v5.4,1` works fine.

Could you please, point me where to search for the ptobkem?

**Environment (if applicable)**

**Additional context**
Chart is pretty simple.
```
const chart = root.container.children.push( am5xy.XYChart.new( root, {

                // "panX": true,
                // "panY": true,
                // "wheelX": "panX",
                // "wheelY": "zoomX",
                // "pinchZoomX": true,
            } ) );

            chart.set(
                "cursor",
                am5xy.XYCursor.new( root, {
                    "behavior": "none", // "zoomX",
                } )
            );

            chart.children.push( am5.Label.new( root, {
                "text": this.l10nd( "vue-ext", "Average duration per call for the last 60 minutes (ms)" ),
                "fontSize": 12,
                "x": am5.percent( 50 ),
                "centerX": am5.percent( 50 ),
            } ) );

            const xAxis = chart.xAxes.push( am5xy.DateAxis.new( root, {
                "baseInterval": {
                    "timeUnit": "minute",
                    "count": 1,
                },
                "renderer": am5xy.AxisRendererX.new( root, {} ),
                "tooltipDateFormat": "HH:mm",
                "tooltip": am5.Tooltip.new( root, {} ),
            } ) );

            const yAxis = chart.yAxes.push( am5xy.ValueAxis.new( root, {
                "renderer": am5xy.AxisRendererY.new( root, {} ),
            } ) );

            const series1 = chart.series.push( am5xy.ColumnSeries.new( root, {
                "name": "Avg. runtime",
                "xAxis": xAxis,
                "yAxis": yAxis,
                "valueXField": "date",
                "valueYField": "duration_per_call",
                "fill": "green",
                "stroke": "green",
                "stacked": true,
                "tooltip": am5.Tooltip.new( root, {
                    "labelText": this.l10nd( "vue-ext", "Duration" ) + ": {valueY} ms",
                } ),
            } ) );

            series1.data.processor = am5.DataProcessor.new( root, {
                "dateFields": ["date"],
                "dateFormat": "i",
            } );
        },
```

**Comment by zdm** [comment]
Seems, that some breaking change was added.

**Comment by xorspark** [comment]
Have you cleared your cache? Your chart renders fine for me: https://codepen.io/team/amcharts/pen/XWywboV/e440d04e5d5a6d52de5da80c89cbb533?editors=0010.

**Comment by zdm** [comment]
Yes, of course
The problem is not in cache.

**Comment by martynasma** [comment]
Does this happen in some particular browser?
Does the CodePen from @xorspark render for you? If it does, can you post something that is broken in 5.4.2 so that we can run and test?

**Comment by zdm** [comment]
I tested in chrome and edge. Not works in both.
I hve no ides how to port my environment to the CodePen. I am using vue + extjs.

**Comment by martynasma** [comment]
What about this CodePen?
https://codepen.io/team/amcharts/pen/XWywboV/e440d04e5d5a6d52de5da80c89cbb533?editors=0010

**Comment by zdm** [comment]
I don;t know how to reproduce it in CodePen.
Amcharts is integrated into the extjs panel, which is integrated into vue component.
The problem is not in the my chart config.
Problem is in the integration.
Something was chanhed in amcharts.

Unclear, what exactly was changed, so I dont know, from what to start.
I already tried varuoys changes - nothing helped

**Comment by martynasma** [comment]
We will investigate. But if you could produce a standalone repro case that would go way faster.

You can create Vue projects on [stackblitz](https://stackblitz.com/).

**Comment by zdm** [comment]
Yes. I un derstand that this is hard to investigate without have code, for reproduction.

O suspect, that problem in the chart size calculation.
Currently it should fill parent div.
Could this been broken?

**Comment by martynasma** [comment]
I agree. Since there are no errors. Just empty charts.

In any case, if you could produce a simple chart with your setup, that would go a long way towards resolving it quickly.

**Comment by zdm** [comment]
Is it possible to get / set chart root el width and heigjt?

**Comment by zdm** [comment]
I want to check that it has non-zero size

**Comment by martynasma** [comment]
Root will always assume size of its container.

I suggest you use developer tools in browser to check actual size of the chart div. Try forcing specific size on it.

**Comment by zdm** [comment]
Parent div is visible, 500 x 300px.
I added border to see dimensions.
When I out some text to this dix - it visible.
But when i create chart root in iths div - is does not visible.

When downgrading to `v5,4,1` - it works.

If parent div is resized  - chart is resized automatically. Correct?

**Comment by martynasma** [comment]
> If parent div is resized - chart is resized automatically. Correct?

That's right.

**Comment by zdm** [comment]
I found the solution.
Created additional child div with width and height = 100% and mount chart root there.

**Comment by Pauan** [comment]
@zdm I tried recreating your code in Vue, but it seems to work fine:

https://stackblitz.com/edit/vue-3y2c5p?file=src%2Fcomponents%2FChart.vue

Could you please fork that StackBlitz and modify it so that it breaks? That way we can see what the problem is.

**Comment by zdm** [comment]
I am using vue + extjs.
Chart mounted to the exrjs panel - this is important.
I think that the problem was in css styles, which extjs added to the panel div.
Previously it worked, but in v5.4.2 you changed something - and it become broken in my case.

**Comment by martynasma** [comment]
@zdm At this point we'll have to augment the stackblitz that @Pauan provided so that it resembles your setup and reproduces the issue, so that we can test properly. Otherwise it's the guesswork on our part.

Hope that sounds reasonable.

**Comment by zdm** [comment]
Ok.
Tell me if you will need something fron mt

**Comment by martynasma** [comment]
Yes, we need you to modify the StackBlitz demo @Pauan posted above to include the modules and other stuff from your setup so that we can reproduce and test the issue.

As it stands now, we're not able to reproduce it, I'm afraid. It's hard to fix bugs that you cannot produce, hence asking for your assitance.

**Comment by zdm** [comment]
The problem is that we need extjs moderv v7.
Extjs is not free and not distributed as external script.

I will try to create repository with sources, which you cal run on your side.

**Comment by zdm** [comment]
https://github.com/zdm/amcharts5-issue-1044

Instructions are in the README.

Tell me, when you will finish, I will removee repo.

**Comment by Pauan** [comment]
@zdm Thank you for providing a repo.

I followed the directions on your repo, but it complained about many missing peerDependencies.

I installed all of the missing peerDependencies, and then I got this error during installation:

```
error /tmp/amcharts5-issue-1044-main/node_modules/@softvisio/uws: Command failed.
```

Could you please verify that the repo installs and runs correctly.

**Comment by zdm** [comment]
hmm, everythis should be installed when you run `npm i`.
Fo you use `npm` or other package manager?

**Comment by zdm** [comment]
also, you need to use latest npm version

**Comment by Pauan** [comment]
@zdm Why does your package require an unstable version of Node and npm?

Your package *should* work correctly with all of the package managers (such as `yarn`), and it should work with the stable version of Node/npm, if it doesn't that's a bad problem.

**Comment by zdm** [comment]
Why unstable? )
We are using features, provided by latest node versions and have no problems.
This id out pilict.

**Comment by zdm** [comment]
<img width="636" alt="image" src="https://github.com/amcharts/amcharts5/assets/1025608/db36f747-556b-4419-9c7e-56d0972f5bcd">

Not errors.

**Comment by Pauan** [comment]
> Why unstable?

The stable version of Node is 18. Node 20 is unstable. Most distros only provide the stable version of Node (for obvious reasons).

>  We are using features, provided by latest node versions and have no problems.

Which Node 20 features are you using?

**Comment by zdm** [comment]
But we are using node 20.
I am unable to downgrade to 18, devause I will need to farebiew a lot of cod.
I am unable to spnd 3 days for this.

I is a real ptoblem for you to run it in the ocker containere with node 20 indtalled?

**Comment by Pauan** [comment]
@zdm I got Node 20 working in a virtual machine, and I was able to reproduce the issue. The fix will be in the next version. Thanks a lot for your help!

**Comment by zdm** [comment]
Thank you very much

**Comment by snigdha920** [comment]
I was also facing the exact same issue in my NextJS project. Looking forward to the next release!

**Comment by martynasma** [comment]
Fixed in [5.4.3](https://github.com/amcharts/amcharts5/releases/tag/5.4.3).

## [5.4.3] - 2023-08-15

### Changed
- Accessibility: focus element of the non-visible focusable items (e.g. buttons) will now have `aria-hidden` attribute set, so they are not read out by screen readers.

### Fixed
- Fixing chart being resized incorrectly inside of nested flexbox. ([Issue 1044](https://github.com/amcharts/amcharts5/issues/1044))
- `SettingsModal` was not being disposed together with a `Root` with a `StockChart` in it.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by snigdha920** [comment]
The version `5.4.3` does not fix the issue for us. Can you please check it again, let me know if you need something from me!

**Comment by martynasma** [comment]
@snigdha920 What about `5.4.4`?

**Comment by snigdha920** [comment]
> @snigdha920 What about `5.4.4`?

This works, thank you!
