### ISSUE TITLE
minGridDistance not working in responsivity rule

### ISSUE THREAD

**Issue by lucasalmeida92** [amcharts/amcharts5#1167]
I'm applying some rules for mobile and for some reason `inside` setting is working but `minGridDistance` is not working :/

Here the reponsive rule:
```js
responsive.addRule({
    name: 'AxisRendererY',
    relevant: isMobile,
    settings: {
      inside: true,
      minGridDistance: 0,
    },
  });
```

Here the creation of yAxis with its renderer:
```js
const yAxis = chart.yAxes.push(
    am5xy.ValueAxis.new(root, {
      extraMax: 0.1,
      renderer: am5xy.AxisRendererY.new(root, {
        strokeOpacity: 0,
        minGridDistance: 220,
        opposite: true,
      }),
      paddingBottom: 16,
    })
  );
```

**Comment by martynasma** [comment]
Fixed in [5.5.5](https://github.com/amcharts/amcharts5/releases/tag/5.5.5).

## [5.5.5] - 2023-11-06

### Added
- SMA line added to Relative Strength Index indicator in `StockChart`.
- A possibility to draw a Parallel Channel added to `StockChart`.

### Changed
- Removed dependency on the `regression` npm package.

### Fixed
- Change of `minGridDistance` setting on `AxisRenderer` was not being applied until next redraw.
- Snapping of `StockChart` drawings sometimes worked incorrectly.
- Average line was drawn incorrectly on a `StockChart` (since `5.5.2`).

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by lucasalmeida92** [comment]
I only tested this out now and is still not working :/

using v5.5.7.

Here the responsive rule:
```js
const responsive = am5themes_Responsive.new(root);
const isMobile = (width) => width < 600;

responsive.addRule({
    name: 'AxisRendererX',
    relevant: isMobile,
    settings: {
      minGridDistance: 10,
    },
});
```

and here the creation of X axes:
```js
const yAxis = chart.yAxes.push(
    am5xy.ValueAxis.new(root, {
      extraMax: 0.1,
      renderer: am5xy.AxisRendererY.new(root, {
        strokeOpacity: 0,
        minGridDistance: 220,
        opposite: true,
        inside: true,
      }),
      paddingBottom: 16,
    })
);
```

**Comment by martynasma** [comment]
Indeed. Something's off. Reopening and investigating.

**Comment by lucasalmeida92** [comment]
Now it worked! Tks very much ;)

**Comment by lucasalmeida92** [comment]
Tried this:
```js
responsive.addRule({
    name: 'AxisRendererY',
    relevant: isMobile,
    settings: {
      minGridDistance: 10,
    },
});
responsive.addRule({
    name: 'AxisRendererY',
    relevant: (width) => !isMobile(width),
    settings: {
      minGridDistance: 220,
    },
});
```
and is not working yet :/

I think the second rule is ovewriting the first one.

**Comment by martynasma** [comment]
Indeed. There's a bug, which we'll fix in the next version.

Will ping you here when the update is out.

**Comment by martynasma** [comment]
Fixed in [5.6.0](https://github.com/amcharts/amcharts5/releases/tag/5.6.0).

## [5.6.0] - 2023-11-26

### Added
- `addBullet(dataItem, bullet)` method added to `Series`. Allows adding a `Bullet` directly to a particular data item instead of adding bullet function to the series. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/#Adding_directly_to_data_item).
- `stacked` (available values: `"up"`, `"down"`,  `"auto"`) setting added to `Bullet`. Allows enabling of automatically stacking bullets on an `XYSeries`. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/#Stacked_bullets).
- `field` (available values: `"open"`, `"high"`, `"low"`, `"value"`) setting added to `Bullet`. Works with `XYSeries` only. Allows setting a particular data field where the bullet should displayed at. Note: `locationX``locationY` settings will be ignored if `field` is set. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/#By_data_field).
- New `Root` element setting: `focusPadding` (default: `2`). Allows specifying distance between focused element and the focus outline.
- Minor grid/labels added on `AxisRenderer` with new settings `minorGridEnabled` and `minorLabelsEnabled` (default: `false`). [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#Minor_grid).
- New setting `minorDateFormats` added to `DateAxis`. Allows setting different formats for minor grid labels. [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Minor_grid_formats).

### Changed
- When `DateAxis` is in weekly grid mode, it will now use `multiLocation` for labels instead of `location`.
- Placement of grid/labels is improved on `DateAxis` and `GaplessDateAxis`.

### Fixed
- Truncating was not working properly on circular labels.
- Fixed potential conflict of responsive rules in `ResponsiveTheme`.
- Issues fixed with data items appearing in wrong place on a chart with data grouping enabled and timezone set.
- `DrawingControl.unserializeDrawings()` method was broken since `5.5.7`.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
