### ISSUE TITLE
Drawing Index issue in the case of polyline

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1376]
In the case of polyline I was facing the issue while deleting the drawing. Both user made drawing and unserialize drawings were deleting.

Steps to reproduce : 

- Unserialize the drawing.
- Then create a ployline
- Then use delete option/button to remove. Both of the drawings will be deleted.

https://github.com/amcharts/amcharts5/assets/137867461/d0445b28-9eac-43dd-a1de-091cf525c3f8

But when I create polyline first then unsearilze the drawings, and then use the delete button it works fine.

Code pen to test : https://codepen.io/Ansh-m-the-reactor/pen/eYoNJNv

**Comment by zeroin** [comment]
I am afraid this is out of scope of free support.

**Comment by workingbuddy10** [comment]
@zeroin this demo is been provided by @martynasma  at #1365 

I have only added the polyline data and now it is not working.

**Comment by workingbuddy10** [comment]
https://github.com/amcharts/amcharts5/assets/137867461/2bfbe1de-f7d4-4c07-864c-ab89c61cbc3a

When we use eraser to erase the user drawn drawings then unseriliase drawings are also removing.
@martynasma you can test this at the above given codepen link!!

**Comment by martynasma** [comment]
It looks like PolyLine tool does not add `drawingId`. We'll look into it.

**Comment by workingbuddy10** [comment]
Thanks @martynasma for considering it!

**Comment by martynasma** [comment]
Fixed in [5.8.5](https://github.com/amcharts/amcharts5/releases/tag/5.8.5).

## [5.8.5] - 2024-03-15

### Added
- `forceHidden` (default: `false`) setting added to `StockControl`. Enables forcing some `StockChart` controls to be always hidden.
- New `DateRangeSelector` event added: `"rangeselected"`.
- New `PriodSelector` event added: `"periodselected"`.

### Fixed
- A JavaScript error was being triggered if a `Picture` was disposed before external image was finished loading (since 5.8.3).
- Inputs in `DateRangeSelector` were ignoring `Root`'s `timezone` and `utc` settings.
- Thicker stroke (`strokeWidth > 1`) was being ignored as a hit target for interactive elements.
- `Scrollbar` grips would not update their position according to `maxZoomCount`/`minZoomCount` setting in some cases.
- Hovering over the border of a `Treemap` node could result tooltip of some other node to appear.
- In some cases pointer over tooltip of a hovered `Treemap` node would remain on the same node, even if pointer would move to some other node.
- If a `{ timeUnit: "week", count: 2 }` (count > 1) was added to a `DateAxis`, labels were flickering while scrolling.
- Calling `zoomToDates()`/`zoomToValues()` on a `DateAxis` was resulting not exact dates when data grouping was enabled and grouping period would changed during zoom.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by workingbuddy10** [comment]
Thanks for the quick upgrade @martynasma 

But the polyline issue is still there.
Case 1: 
- Unserialize the drawing.
- Create the polyline using drawing tool.
- And then delete the Unserialize drawings using the button "delete" given.

Case 2: 
- Unserialize the drawing.
- Create the polyline using drawing tool.
-  And then delete the drawings using the in-built feature of amcharts delete all button of stock chart.

https://codepen.io/Ansh-m-the-reactor/pen/eYoNJNv

**Comment by martynasma** [comment]
It works fine for me in both cases. Did you clear your browser cache?

**Comment by workingbuddy10** [comment]
Yes now it worked for me, I had only refreshed the app.
Thanks @martynasma ! 💯
