### ISSUE TITLE
Prevent focus in Label Tool Drawings

### ISSUE THREAD

**Issue by shishima123** [amcharts/amcharts5#1702]
How to disable focus on label every time chart is initialized?

Additionally, how can I disable the drag function of the icon and label when the drawing feature is disabled?

https://github.com/user-attachments/assets/ff4afba8-77f5-4ec8-84bb-c68c2b5d1ac5

**Comment by martynasma** [comment]
Fixed in [5.10.5](https://github.com/amcharts/amcharts5/releases/tag/5.10.5).

## [5.10.5] - 2024-09-06

### Added
- `scrollToChild()` method added to `Container`. Scrolls the container to the target child element if the container is scrollable and the element is currently outside of view.
- New `StockChart` drawing tool added: "Line Arrow".

### Changed
- When a selected drawing in a `StockChart` is inselected by clicking on a chart's plot area the new drawing will not be added anymore.

### Fixed
- Keyboard-dragging of focusable elements was not working correctly in some cases.
- Sometimes label/callout drawing text was cut temporarily while editing them on `StockChart`.
- Editable labels/callouts would go into edit mode when unserialized.
- If auto-saving of drawings was enabled, editing text would not always save the latest version of the label/callout text.
- Dragging a `StockChart` drawing while other drawing was selected, would drag the selected drawing as well.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by shishima123** [comment]
Thank you @martynasma 
I noticed that the issue of being able to drag the icon and label when the draw mode is off still exists.

Do you have any plans to improve this?

Being unable to drag when the draw mode is off is important, as it will help prevent users from accidentally interacting with the drawing while working with the chart


https://github.com/user-attachments/assets/49b4dd2d-a30c-4c5d-b0dc-7ffa1b572b99

**Comment by martynasma** [comment]
Would you be able to please post it as a separate issue? Just to avoid the mess.
