### ISSUE TITLE
Wrong placement of tooltip pointer when it is oblique

### ISSUE THREAD

**Issue by datafoo** [amcharts/amcharts5#301]
### Steps to reproduce

1. Configure a chart with a series tooltip using `pointerOrientation: "horizontal"` and `strokeWidth` with a value greater than 1 (see https://codepen.io/jackfoo/pen/bGYMJQY)
2. Hover over the series to display a tooltip that has an oblique pointer

### Expected result:
The tip of the pointer should point exactly to the precise location of the data item.

### Actual result
The tip of the pointer is shifted vertically from the precise location. The shift seems to be equal to `strokeWidth`.

**Comment by martynasma** [comment]
Well, the pointer is in the right place. However it's encircled with a thick outline, which makes it seem like pointer is extending further than it is.

You may adjust tooltip position using `dx` and `dy` settings, e.g.:

```JavaScript
var tooltip = am5.Tooltip.new(root, {
  labelText: "{categoryX}: {valueY}",
  pointerOrientation: "horizontal",
  dy: -3,
  dx: 3
});
```

**Comment by datafoo** [comment]
> Well, the pointer is in the right place. However it's encircled with a thick outline, which makes it seem like pointer is extending further than it is.

The "right place" does not seem right. Perhaps the "tip" of the pointer should by definition include any stroke and calculate its position accordingly.

> You may adjust tooltip position using `dx` and `dy` settings, e.g.:
> 
> ```js
> var tooltip = am5.Tooltip.new(root, {
>   labelText: "{categoryX}: {valueY}",
>   pointerOrientation: "horizontal",
>   dy: -3,
>   dx: 3
> });
> ```

With `pointerOrientation: "horizontal"`, I cannot predict if the pointer is going to be on the left or right so the workaround does not work in all the cases. See result last data item in https://codepen.io/jackfoo/pen/xxPjvxy

Also, there are some sinus and cosinus of the angles of the pointer edges to find the proper numbers. Empirically, this gives better results:

```js
var tooltip = am5.Tooltip.new(root, {
  labelText: "{categoryX}: {valueY}",
  pointerOrientation: "horizontal",
  dy: -4.7,
  dx: 3.4
});
```

**Comment by martynasma** [comment]
Thanks.

We've decided implement a placement fix in the next version.

Will let you know when new version is out.

**Comment by martynasma** [comment]
Fixed in [5.1.7](https://github.com/amcharts/amcharts5/releases/tag/5.1.7).

## [5.1.7] - 2022-02-28

### Fixed
- Grouping to periods where `timeUnit` was `"day"` and `count > 1` was not working properly.
- When tooltips of multiple series were pointing at the same point, series order was not being respected (FF only).
- If a scrollbar was added before axes, scrolling series could result series to be out of sync with bullets.
- Tweaked `nb_NO` locale to better correspond to Norwegian Bokmål date formats.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by datafoo** [comment]
No mention was made of this issue in the changelog for 5.1.7.

The issue is still present on my side.

**Comment by martynasma** [comment]
Sorry about that. Our bad. Somehow that fix did not make into changelog.

There was a fix implemented, and I'm getting correct horizontal position now.

Vertically, however, there's still visible shift when tooltip target is partially outside of the plot area, which we'll need to fix. 

Reopening.

**Comment by datafoo** [comment]
> There was a fix implemented, and I'm getting correct horizontal position now.
> 
> Vertically, however, there's still visible shift when tooltip target is partially outside of the plot area, which we'll need to fix.

I still have wrong positioning on my side, both horizontally and vertically. It is easier to see with wider stroke (`strokeWidth: 5`).

**Comment by martynasma** [comment]
OK, so after thorough evaluation, we won't be able to make tooltip adjust its tip according to `strokeWidth` when pointing outside plot area. The amount of fuzzy logic would be to big. Sorry.

**Comment by sassomedia** [comment]
> With `pointerOrientation: "horizontal"`, I cannot predict if the pointer is going to be on the left or right so the workaround does not work in all the cases. See result last data item in https://codepen.io/jackfoo/pen/xxPjvxy

@datafoo fyi, you can predict where the pointer is by controlling the orientation and positioning:
https://codepen.io/sassomedia/pen/wvPRwbo?editors=0010
