### ISSUE TITLE
Non predictable tooltips order with stacked series

### ISSUE THREAD

**Issue by datafoo** [amcharts/amcharts5#304]
### Steps to reproduce

1. Configure a chart with several stacked series and series tooltip (see https://codepen.io/jackfoo/pen/rNYKBmN)
2. Hover over the series to display the tooltips

### Expected result:
The tooltips should always be ordered in the same order as the stacked series.

Why? It is mentally easier to scan through the tooltips if they are always in the same order. Is is confusing to see the order of the tooltips changing when hovering from one data item to another.

### Actual result
The tooltips are not always ordered in the same order as the stacked series.

**Comment by zeroin** [comment]
Thanks, we will adjust this in next release.

**Comment by martynasma** [comment]
Fixed in [5.1.6](https://github.com/amcharts/amcharts5/releases/tag/5.1.6).

## [5.1.6] - 2022-02-23

### Fixed
- Totals were not calculated until some interaction with `XYChart` chart if data was grouped initially.
- When tooltips of multiple series were pointing at the same point, series order was not being respected.
- Reverting "Fixing ES6 module detection by BundlePhobia" from 5.1.5 which was causing issues.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by datafoo** [comment]
It does not seem to be fixed. I can still reproduce with the codepen indicated above.

Same problem with 5.1.6 on my real project.

**Comment by martynasma** [comment]
Did you clear your browser cache? I can't seem to be able to reproduce this with the above CodePen anymore.

**Comment by datafoo** [comment]
I did and it seems the problem only persist on Firefox. Tested with Firefox 97.0.1 (64-bit) on Windows and 95.0.2 (64-bit) on GNU/Linux.

**Comment by martynasma** [comment]
OK, I can see that. Reopening.

**Comment by martynasma** [comment]
Fixed in [5.1.7](https://github.com/amcharts/amcharts5/releases/tag/5.1.7).

## [5.1.7] - 2022-02-28

### Fixed
- Grouping to periods where `timeUnit` was `"day"` and `count > 1` was not working properly.
- When tooltips of multiple series were pointing at the same point, series order was not being respected (FF only).
- If a scrollbar was added before axes, scrolling series could result series to be out of sync with bullets.
- Tweaked `nb_NO` locale to better correspond to Norwegian Bokmål date formats.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
