### ISSUE TITLE
Chart Controls Date Picker CSS Imperfection

### ISSUE THREAD

**Issue by cwooldridge1** [amcharts/amcharts5#446]
Whenever the chart size drops below ~1135px on your guy's site the data pickers year-selector halfway disappears and the input forms also are offset. The ~1135px benchmark varies from site to site based on the underlying sites @media breakpoints however in my application no matter how big it is I get the same issue that is apparent on your guy's site at ~1135. Thought I'd point this out, thanks for all your time. 
<img width="675" alt="image" src="https://user-images.githubusercontent.com/85259389/171056139-c9b3a081-1b0a-4e8c-a516-cbc0c7f8552a.png">
Image source: https://www.amcharts.com/demos/stock-chart-comparing-prices/

**Comment by martynasma** [comment]
Fixed in [5.2.7](https://github.com/amcharts/amcharts5/releases/tag/5.2.7).

## [5.2.7] - 2022-06-07

### Added
- `minDistance` to `LineSeries` (default: 0). If set, it will skip line points closer than X pixels, resulting in a smoother, less cluttery line.
- `isVisibleDeep()` method to `Sprite`. Check not only if `Sprite` itself is visible, but also its all ascendants.

### Changed
- TAB press should now skip over focusable elements of hidden series.

### Fixed
- Toggling `PieSeries` `alignLabels` after the chart was initialized was not working.
- Fixing bug where the wheel event would sometimes not trigger.
- When setting `stockSeries` with a new series on `StockChart` it was not inheriting `stockPositiveColor`/`stockNegativeColor` values.
- Tweaked default `StockToolbar` CSS to act better on pages with larger font sizes.
- DOM elements for focusable series items (columns, bullets, etc.) were being left behind when data for series was updated.
- Exporting chart to image was not inheriting document styles properly.
- If stock series increase/decrease colors were changed and then a series type was changed, new series used to reset colors and not use the ones user set.
- Dynamically changing page-wide font-related CSS (e.g. via media queries) could cause visual anomalies on the chart, especially on axes.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by cwooldridge1** [comment]
Hey I recently updated to the new version and I still have this issue. Any ideas?
