### ISSUE TITLE
Charts are horizontally shaking

### ISSUE THREAD

**Issue by fgleyze** [amcharts/amcharts5#447]
**Bug description**

We have many different AM Charts on our website and some of them are randomly shaking. We noticed this behavior on `SmoothedXLineSeries` and `ColumnSeries` charts.

Among other things, we changed our chart container from fluid to fix width and we removed the `appear()` animation, without any success.

Here is [a small GIF of the glitch](https://ibb.co/58SFPcx) : it shakes must faster on screen.

**Environment**

 - amCharts 5.2.2
 - Chrome 98.0.4758.80
 - React 18.1, TypeScript
 
 Thanks for your help !

**Comment by xorspark** [comment]
Would it be possible to share a minimal codepen of your setup that reproduces this?

**Comment by martynasma** [comment]
Thanks for additional details.

While we still can't reproduce your current setup, I believe we have made some changes that should solve this.

I'll let you know when the new version is out, so that you can check if that solved the issue on your end.

**Comment by martynasma** [comment]
Fixed in [5.2.7](https://github.com/amcharts/amcharts5/releases/tag/5.2.7).

## [5.2.7] - 2022-06-07

### Added
- `minDistance` to `LineSeries` (default: 0). If set, it will skip line points closer than X pixels, resulting in a smoother, less cluttery line.
- `isVisibleDeep()` method to `Sprite`. Check not only if `Sprite` itself is visible, but also its all ascendants.

### Changed
- TAB press should now skip over focusable elements of hidden series.

### Fixed
- Toggling `PieSeries` `alignLabels` after the chart was initialized was not working.
- Fixing bug where the wheel event would sometimes not trigger.
- When setting `stockSeries` with a new series on `StockChart` it was not inheriting `stockPositiveColor`/`stockNegativeColor` values.
- Tweaked default `StockToolbar` CSS to act better on pages with larger font sizes.
- DOM elements for focusable series items (columns, bullets, etc.) were being left behind when data for series was updated.
- Exporting chart to image was not inheriting document styles properly.
- If stock series increase/decrease colors were changed and then a series type was changed, new series used to reset colors and not use the ones user set.
- Dynamically changing page-wide font-related CSS (e.g. via media queries) could cause visual anomalies on the chart, especially on axes.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by crypto-services** [comment]
I can confirm this still exists in the latest version. The issue appears to be not setting font type. 

Setting font to "Roboto" or "Poppins" causes it to glitch on load about 70% of the time. Declaring the type of your font (i.e. '"Roboto", monospace' or '"Poppins", san-serif') seems to stop it. 

Additionally setting the width or height of the axis labels stops it. Zooming to the point where the axis resizes also causes it to stop, I assume it's getting the actual width on redraw. 

Hope that helps someone!

**Comment by jessebrightman** [comment]
I am also experiencing this on the current version on almost every page load.  It is rendering the chart unusable.  I have tried to change the fonts as shown above but it does not help.  It seems like a listener or resize issue.  Is there any update on a fix?  We are on a paid subscription.

**Comment by xorspark** [comment]
@jessebrightman - If you could provide a minimal repro codepen/stackblitz, that would really help us come up with a more targetted fix.

**Comment by sassomedia** [comment]
@xorspark I have only seen this issue once but I couldn't recreate it. What I did notice however is that something with the chart's resizing must have been updated as that is no longer working as before. This could be related to the shaking where the resize logic is fighting the scaling of the chart. The issue that I _can_ reproduce is in the following scenario:

- Two divs in a flexbox, side-by-side. The left one (chart) is 100%, the right one has a fixed size.
- The right div can be toggled to expand/shrink, which causes the left div (chart) to shrink/expand accordingly.
- This used to work in version 5.2.2 but after updating to 5.2.22, this does not work anymore.
- The chart no longer shrinks when the right div is toggled. The chart however does resize when the whole window is resized.

The Codepen [here](https://codepen.io/sassomedia/pen/QWrdovV?editors=1000) demonstrates the working resize on an empty test div. If that div gets commented out and the chart gets put back in, the right div will no longer resize.
