### ISSUE TITLE
Selected event not calling on Indicator Control

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#566]
I am trying to get selected indicator name or id from the indicator dropdown,
but the click event is running on clicking on the Indicator Button.

after that i set the selected event but that event is not calling. (i think it is because of the Indicator Button is differ from the indicator dropdown list. but in the Comparision Control i used same event and it is working there as needed.)

```
indicatorControl.events.on("selected", function (ev) {
  alert("I am Selected")
  console.log("selected: "+ ev)
});
indicatorControl.events.on("click", function(ev) {
  alert("I am Clicked")
  console.log("click: "+ev)
});
```
Click on indicator control you will see the alert, but clicking on dropdown item not shows alert.
Check my code: https://codepen.io/team/amcharts/pen/jOzvvMM?editors=0010

Please check...

**Comment by martynasma** [comment]
It's a bug. We'll fix it in the next version.

Thanks for the heads up!

**Comment by martynasma** [comment]
Fixed in [5.2.18](https://github.com/amcharts/amcharts5/releases/tag/5.2.18).

## [5.2.18] - 2022-08-24

### Added
- `disabled` key support added to `DropdownList` item interface.

### Fixed
- Removed leftover debug code in `IndicatorControl`.
- `selected` event in `IndicatorControl` was not firing.
- Adding an adapter on Y-axis' labels could cause flickers on the chart.
- `maxWidth`/`maxHeight` of a `Container` was ignored when arranging objects by Horizontal or Vertical layout.
- `maxWidth`/`maxHeight` of a `Container` was ignored when drawing background.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by mukeshbadgujar** [comment]
Still Not Working!!!
Please Check

https://jsfiddle.net/mukeshbadgujar/2m398n4o/2/

**Comment by martynasma** [comment]
Turns out we had issues with out CDN. Should be fine now.

Sorry for the inconvenience.

**Comment by mukeshbadgujar** [comment]
@martynasma Sorry but it is still not working. Please Check

https://jsfiddle.net/mukeshbadgujar/2m398n4o/2/

**Comment by martynasma** [comment]
It is working for me:

![image](https://user-images.githubusercontent.com/1458520/186848990-38aaf865-8542-41e9-bcc6-70a348dbe7c6.png)

Please make sure you clear your browser cache.

**Comment by mukeshbadgujar** [comment]
Now Working... Thanks
