### ISSUE TITLE
When grouping is done last value is getting hided behind the yaxis value and default selecteriod is not getting selected

### ISSUE THREAD

**Issue by VanavarayanK** [amcharts/amcharts5#723]
Hi,

In stock chart when group is enabled when it comes to week or month the last point of chart is getting hide behind the yaxis values then we want to scroll towards left and check that value is there any way to overcome this issue 
Example: when i select 6m as default  this is not getting selected in the toolbar also last value show 5th of Dec if scroll left and check 12th dec is showing which is hided
![image](https://user-images.githubusercontent.com/118241594/208029930-28a5bbc5-a793-4422-aa57-5574ab53c3b5.png)
![image](https://user-images.githubusercontent.com/118241594/208029970-776bd50d-f6b7-49ca-9ecb-d35147d6ad1c.png)

https://jsfiddle.net/4rfeLpxk/18/

**Comment by martynasma** [comment]
Fixed in [5.2.42](https://github.com/amcharts/amcharts5/releases/tag/5.2.42).

## [5.2.42] - 2022-12-16

### Added
- `reverseGeodata` setting added to `MapPolygonSeries`. If set to `true`, will reverse direction of polygon corners in GeoJSON.
- `linechanged` event added to MapLine.

### Fixed
- If a chart had multiple vertically stacked Y axes and `snapToSeries` was set, moving mouse to series in the bottom could cause chart cursor to disappear.
- A legend label for a `ZigZag` indicator was showning "NaN" instead of its `depth` value.
- Hierarchy series' `topDepth` setting was not working properly if set to `>1`.
- If a `Sprite` was hidden, it hid it's tooltip even if the tooltip at the moment was used by other element. This caused some wrong behavior with Axis tooltips, as all axis elements share the same tooltip.
- If a `MapLine` was changed and some `MapPoint` was assigned to this line, `MapPoint` was not always updating its position.
- Map with `geoAlbersUsa` projection was not working if `GraticuleSeries` was added to it.
- `MapLine` was showing tooltips in a wrong position (in case lines were not straight).
- `PeriodSelector` was not properly zooming whe data grouping was enabled.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by VanavarayanK** [comment]
Hi Team,

Sorry for the late reply.

Still facing the  same problem  in IOS after upgrading, zooming is not
working properly also default value in the toolbar is not getting selected
until we click on periods like below.


[image: image.png]

In Android
[image: image.png]

In IOS
[image: image.png]

**Comment by martynasma** [comment]
The jsFiddle you posted works good for me now. Or is this related to https://github.com/amcharts/amcharts5/issues/719?

**Comment by VanavarayanK** [comment]
Yes, In web browsers it works fine whereas if we try to use this  in mobile
application or ios browers from mobile u will get to know the difference as
above image,only  IOS users facing this issue. Also in JSfiiddle forcefully
i have added a active class  by using below code,  that should not be the
case if we give selectPeriod as 1month then it should take automatically
that is not happening right now.

let divID = document.getElementsByClassName("am5stock-link")
 divID[1].className += "   am5stock-active";

**Comment by martynasma** [comment]
Let's not keep a mess of two threads. If it's about the same as issue as https://github.com/amcharts/amcharts5/issues/719, let's keep conversation there.

Please also post the className thing as a separate issue.

**Comment by VanavarayanK** [comment]
Sure, will do that.
